### ISSUE TITLE
Issue with User Credentials

### ISSUE THREAD

**Issue by maheshrajrp** [n8sOrganization/vCluster-OIDC#1]
Hi,
I am facing issue with user-credentials, where I am not receiving any email and other information related to OIDC in Config. The following is my values.yaml

```
api:
  extraArgs:
    - --oidc-issuer-url=https://tech.com/auth/realms/tech
    - --oidc-client-id=tech-sso
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
init:
  manifestsTemplate: |-
    ---
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: oidc-cluster-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - kind: Group
      name: {{ .Values.ClusterAdminGroup }}
service:
  type: LoadBalancer
  loadBalancerAnnotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

When I run this with the helm, I am not getting proper config as mentioned in the Documentation. I am getting something like this,

```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <base64string>
      server: https://localhost:8443
    name: my-vcluster
contexts:
  - context:
      cluster: my-vcluster
      user: my-vcluster
    name: my-vcluster
current-context: my-vcluster
kind: Config
preferences: {}
users:
  - name: my-vcluster
    user:
      client-certificate-data: <base64string>
      client-key-data: <base64string>
```

It would be great if someone could help me with this.

Thanks
